module.exports = {
  game: {
    _id: '5eb23f22086cf5841ff7305c',
    name: 'aut et quo',
    image: 'http://lorempixel.com/640/480/business',
    announcements: [
      {
        _id: '5eb23f22086cf5841ff7305d',
        title: 'Quas ipsum et animi earum atque aliquam.',
        postDate: '2020-05-05T13:06:13.318Z',
        body: 'Modi est eligendi eveniet itaque. Voluptates amet sint ullam dolor laboriosam neque sit assumenda. Architecto dolores omnis. Quibusdam omnis autem molestiae ea in saepe ex. Aut aliquid maxime aut iusto doloremque repellendus necessitatibus consequatur.\n \rEx aut inventore enim molestiae vel autem est. At adipisci libero reiciendis enim rerum labore perferendis accusantium ipsa. Corporis fugit rem aliquam optio iste accusantium dolorum natus corrupti. Culpa est aliquam error. Animi adipisci omnis velit facere incidunt sit non ullam quia. Tempore necessitatibus dignissimos veniam.\n \rEos ut nesciunt ab dolores commodi qui. Neque dolorem aliquam nihil non sed. Error provident harum in sunt nobis ab qui et quod. Porro voluptas vitae sed sed iste expedita. Voluptatem exercitationem ut error itaque laudantium quidem.',
        category: 'event',
        url: 'http://myles.org',
        thumbnailUrl: 'https://steamcdn-a.akamaihd.net/steam/apps/10150/0000008861.600x338.jpg?t=1534443367',
        rateUp: null,
        rateDown: null,
        commentCount: 16,
        likes: 48,
      },
      {
        _id: '5eb23f22086cf5841ff7305e',
        title: 'Omnis adipisci occaecati assumenda quis natus.',
        postDate: '2020-05-05T17:24:40.731Z',
        body: 'Magnam sapiente omnis possimus vitae. Labore quas sed ipsum veniam aut sint autem excepturi. Tenetur sint voluptatem laboriosam qui iure maxime aspernatur sapiente. Harum est natus qui ipsam soluta dolore quia.\n \rEst sed accusantium. Non ratione enim non non at. Voluptatem consequatur nihil qui est maxime tempore non dolore nihil. Delectus tempore eum. Quia sit eaque quia autem nihil aut quod debitis voluptatibus.\n \rAut est dolore quaerat dolor minima sit voluptatem est qui. Id placeat porro officiis labore voluptas doloribus blanditiis non. Ut quibusdam exercitationem voluptatibus iusto fugiat dolores enim.',
        category: 'announcement',
        url: 'http://keshawn.info',
        thumbnailUrl: 'https://steamcdn-a.akamaihd.net/steamcommunity/public/images/clans/36225228/efee37e07322802794443f01eda517422f667887_960x311.jpg',
        rateUp: null,
        rateDown: null,
        commentCount: 32,
        likes: 97,
      },
      {
        _id: '5eb23f22086cf5841ff7305f',
        title: 'Voluptatum autem molestias ipsum.',
        postDate: '2020-05-05T07:33:36.698Z',
        body: 'Quisquam rerum nihil laboriosam perferendis vero voluptates. Excepturi est sapiente non alias ut quibusdam quas. Vel veniam laudantium saepe ratione voluptate. Quis saepe est odio. Dolorem quia tenetur omnis ducimus est quo quis velit quia.\n \rOdit nam in ut a officia mollitia ut vel facilis. Ut aliquam possimus tempora. Nulla iure dolores similique sit. Dolores libero ab ut ea ullam id et architecto. Voluptates quis ut amet iure ea aspernatur dolores expedita animi.\n \rDolore velit sunt rem illo dolores eos. Et possimus cumque excepturi omnis laborum. Porro eum odit voluptate dolor earum commodi a modi.',
        category: 'announcement',
        url: 'http://jaclyn.info',
        thumbnailUrl: 'https://steamcdn-a.akamaihd.net/steam/apps/15100/header.jpg?t=1532007211',
        rateUp: true,
        rateDown: false,
        commentCount: 8,
        likes: 43,
      },
      {
        _id: '5eb23f22086cf5841ff73060',
        title: 'At ea sed perspiciatis fugiat.',
        postDate: '2020-05-05T23:17:49.097Z',
        body: 'Quasi et beatae. Repudiandae ullam omnis earum consequatur. Voluptatibus commodi earum blanditiis totam dolores tempore et. Architecto quod animi qui quia eaque neque. Est totam ut.\n \rModi est non. Ut vel eum est. In consequatur nostrum illo non ratione et ut et. Rerum tempora adipisci rerum. Animi dolor laudantium exercitationem dolor quas mollitia cumque odio officia.\n \rQui modi unde. Quis veritatis in aliquid modi omnis. Qui voluptatum natus quia. Nesciunt nisi ut distinctio a illum id nulla tenetur. Et rerum natus et sed et ratione cupiditate quibusdam. Iusto consequatur quis nisi quibusdam laboriosam nihil ratione modi.',
        category: 'announcement',
        url: 'https://chaim.org',
        thumbnailUrl: 'https://steamcdn-a.akamaihd.net/steam/apps/13500/header.jpg?t=1447351266',
        rateUp: null,
        rateDown: null,
        commentCount: 10,
        likes: 79,
      },
      {
        _id: '5eb23f22086cf5841ff73061',
        title: 'Vel consequatur non explicabo accusantium quae nam',
        postDate: '2020-05-05T05:03:42.490Z',
        body: 'Ea dignissimos tenetur unde. Error eligendi voluptas aliquam quas. At quibusdam aperiam illum at repellendus iste natus. Rerum quos quibusdam eius minus necessitatibus numquam aperiam dolor quasi. Ut aperiam debitis occaecati rem qui aliquid qui atque aut.\n \rRatione voluptatem aut eius fuga explicabo odio sunt sed adipisci. Non beatae mollitia. Occaecati qui accusamus numquam voluptatem voluptatum repellendus nulla ducimus et.\n \rQuia repellat quisquam nesciunt dignissimos mollitia velit ea ducimus. Ut enim cupiditate eum occaecati id id recusandae. Velit id aspernatur quia in est. Autem voluptatem corporis fugiat atque voluptatibus ad velit.',
        category: 'announcement',
        url: 'https://mozell.net',
        thumbnailUrl: 'https://steamcdn-a.akamaihd.net/steam/apps/13500/header.jpg?t=1447351266',
        rateUp: null,
        rateDown: null,
        commentCount: 34,
        likes: 32,
      },
      {
        _id: '5eb23f22086cf5841ff73062',
        title: 'Soluta atque est velit.',
        postDate: '2020-05-06T02:37:06.235Z',
        body: 'Iure qui error modi maxime. Repudiandae similique laborum ad voluptates. Rerum autem optio. A id dolores voluptatem optio.\n \rNihil incidunt voluptatem et fugiat explicabo. Temporibus eum asperiores aut et nam saepe sunt dolores totam. Quod cumque quidem. Quia sit vel hic consequuntur sed modi deserunt. Voluptatem vero ea voluptatem architecto quam et doloremque aliquid adipisci.\n \rDolores et non quisquam quidem rerum. Atque beatae in at. Error autem eveniet aut atque. Omnis quos delectus iure aut numquam ratione ut.',
        category: 'announcement',
        url: 'https://desiree.com',
        thumbnailUrl: 'https://steamcdn-a.akamaihd.net/steam/apps/10150/0000008861.600x338.jpg?t=1534443367',
        rateUp: true,
        rateDown: false,
        commentCount: 12,
        likes: 28,
      },
      {
        _id: '5eb23f22086cf5841ff73063',
        title: 'At consectetur minus eligendi illum dignissimos so',
        postDate: '2020-05-05T16:47:01.078Z',
        body: 'Autem explicabo tenetur placeat. Laborum voluptate consequatur illum voluptatem natus et laborum vel quis. Ut aliquam molestiae et nostrum placeat.\n \rMollitia earum praesentium laudantium culpa non non. Sunt corporis debitis dolor quos voluptatem non accusantium officia odit. Non ratione eligendi dignissimos impedit aliquam similique incidunt consequuntur voluptatem.\n \rDolorem ut pariatur voluptatibus quaerat ad. Perferendis quam est. Tenetur et vero consequuntur. Et quia iure et optio aliquam commodi et nihil. Ad cupiditate voluptatem quisquam et laboriosam voluptatem soluta corrupti et.',
        category: 'announcement',
        url: 'https://edwina.net',
        thumbnailUrl: 'https://steamcdn-a.akamaihd.net/steamcommunity/public/images/clans/35210272/1d23fd0d78c84916ed943ae0410cd77adb6eff46.jpg',
        rateUp: true,
        rateDown: false,
        commentCount: 17,
        likes: 88,
      },
      {
        _id: '5eb23f22086cf5841ff73064',
        title: 'Sit velit deserunt quibusdam ipsa quam eligendi ve',
        postDate: '2020-05-06T01:42:16.166Z',
        body: 'Libero ullam repellendus. Dolorem placeat et minima eius voluptas natus. In impedit sapiente qui molestiae et nihil et explicabo.\n \rIpsum amet ab quam in quas. Reprehenderit dolorem amet voluptatum esse. Fuga ad ut aperiam explicabo expedita minima et et. Expedita ratione temporibus fugit repellat laborum quo quos accusamus.\n \rEt nulla eveniet error veniam. Voluptatum id sunt ut nesciunt quidem explicabo id. Aut aut et ut aliquam aut sunt vitae.',
        category: 'announcement',
        url: 'https://hollie.net',
        thumbnailUrl: 'https://steamcdn-a.akamaihd.net/steamcommunity/public/images/clans/36260268/0201fd67aef0968802adc9c24473860baa3f39ab_960x311.jpg',
        rateUp: false,
        rateDown: true,
        commentCount: 11,
        likes: 3,
      },
      {
        _id: '5eb23f22086cf5841ff73065',
        title: 'Laborum quidem vel dignissimos.',
        postDate: '2020-05-05T18:39:09.628Z',
        body: 'Eum error est qui et sit enim accusantium eos. Eligendi ut laudantium consequatur vitae assumenda ut. Aut dicta alias voluptatibus. Magni corporis ab. Rerum odio exercitationem iste impedit molestiae provident.\n \rAut voluptas ipsum perspiciatis dolores velit saepe vitae minima voluptatem. Animi expedita est voluptas consequatur voluptas omnis voluptas possimus. Fugiat vitae qui blanditiis. Aut enim assumenda natus omnis quas et sapiente. Praesentium temporibus id perspiciatis nesciunt odit impedit cum odio recusandae. Rem minus et fugit dolore harum.\n \rCorrupti hic unde. Ipsum assumenda at. Recusandae atque illo corrupti quos quibusdam aliquid. Magni mollitia et doloribus itaque.',
        category: 'announcement',
        url: 'https://elnora.biz',
        thumbnailUrl: 'https://steamcdn-a.akamaihd.net/steamcommunity/public/images/clans/36260268/31e792edea8b4d5a9c5e4cbbc85ba024445dd07f_960x311.jpg',
        rateUp: null,
        rateDown: null,
        commentCount: 4,
        likes: 52,
      },
    ],
    url: 'http://adrianna.com',
    __v: 0,
  },
  eventItem: {
    _id: '5eb23f22086cf5841ff7305d',
    title: 'Quas ipsum et animi earum atque aliquam.',
    postDate: '2020-05-05T13:06:13.318Z',
    body: 'Modi est eligendi eveniet itaque. Voluptates amet sint ullam dolor laboriosam neque sit assumenda. Architecto dolores omnis. Quibusdam omnis autem molestiae ea in saepe ex. Aut aliquid maxime aut iusto doloremque repellendus necessitatibus consequatur.\n \rEx aut inventore enim molestiae vel autem est. At adipisci libero reiciendis enim rerum labore perferendis accusantium ipsa. Corporis fugit rem aliquam optio iste accusantium dolorum natus corrupti. Culpa est aliquam error. Animi adipisci omnis velit facere incidunt sit non ullam quia. Tempore necessitatibus dignissimos veniam.\n \rEos ut nesciunt ab dolores commodi qui. Neque dolorem aliquam nihil non sed. Error provident harum in sunt nobis ab qui et quod. Porro voluptas vitae sed sed iste expedita. Voluptatem exercitationem ut error itaque laudantium quidem.',
    category: 'event',
    url: 'http://myles.org',
    thumbnailUrl: 'https://steamcdn-a.akamaihd.net/steam/apps/10150/0000008861.600x338.jpg?t=1534443367',
    rateUp: false,
    rateDown: true,
    commentCount: 16,
    likes: 48,
  },
  announcementItem: {
    _id: '5eb23f22086cf5841ff7305e',
    title: 'Omnis adipisci occaecati assumenda quis natus.',
    postDate: '2020-05-05T17:24:40.731Z',
    body: 'Magnam sapiente omnis possimus vitae. Labore quas sed ipsum veniam aut sint autem excepturi. Tenetur sint voluptatem laboriosam qui iure maxime aspernatur sapiente. Harum est natus qui ipsam soluta dolore quia.\n \rEst sed accusantium. Non ratione enim non non at. Voluptatem consequatur nihil qui est maxime tempore non dolore nihil. Delectus tempore eum. Quia sit eaque quia autem nihil aut quod debitis voluptatibus.\n \rAut est dolore quaerat dolor minima sit voluptatem est qui. Id placeat porro officiis labore voluptas doloribus blanditiis non. Ut quibusdam exercitationem voluptatibus iusto fugiat dolores enim.',
    category: 'announcement',
    url: 'http://keshawn.info',
    thumbnailUrl: 'https://steamcdn-a.akamaihd.net/steamcommunity/public/images/clans/36225228/efee37e07322802794443f01eda517422f667887_960x311.jpg',
    rateUp: true,
    rateDown: false,
    commentCount: 32,
    likes: 97,
  },
};
